language: go

go:
  - 1.12
  - 1.13
  - master

sudo: false

env:
  - GO111MODULE=on

install:
  - go mod download

script:
  - make example
  - if [ "$TRAVIS_GO_VERSION" != "1.13" ]; then make test      ; fi
  - if [ "$TRAVIS_GO_VERSION" == "1.13" ]; then make test-cover; fi
